#!/usr/bin/env python3
"""Q4 phase 6: write the Q4 tables and design-note section from the measured JSON.

Every number in the two outputs is read from reports/q4_*.json, so the prose can
never drift from the measurements; re-running any phase and then this script
refreshes both documents.

  reports/q4_summary.md      all Q4 tables (setup, correctness, memory, latency,
                             cost, 10x scale) with assumptions and caveats
  reports/design_note_q4.md  the Q4 section of the design note (Q6)

Usage
-----
    python src/serving/q4_report.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

REPORTS = REPO_ROOT / "reports"
DATASETS = ("mind", "ebnerd")
LABEL = {"mind": "MIND-small", "ebnerd": "EB-NeRD small"}
STAGES = ("profile", "bm25", "faiss", "popularity", "merge", "features", "nrms", "sort")
WHAT = {  # dataset-neutral descriptions; the per-dataset JSON "what" strings embed MIND/EB-NeRD sizes
    "stage1/faiss_flat_index (pool)": "exact FAISS index over the circulating pool",
    "stage1/a1_article_embeddings": "A1 article embeddings (float32), for each user's query vector",
    "stage1/bm25_weights (doc x term)": "sparse BM25 weight matrix",
    "stage1/bm25_weights_t (term x doc)": "the same weights transposed, kept for fast scoring",
    "stage1/bm25_vocabulary": "term → column dict",
    "stage1/bm25_other": "idf, document ids and lengths",
    "stage1/popularity_ranker": "train-click ranking",
    "stage1/pool_index": "circulating-pool rows + id set",
    "stage1/article_tokens+ids": "article tokens BM25 queries are built from",
    "stage1/user_profile_store": "every user's full click history",
    "cache/bm25_pooled_weights_t": "pool-sliced BM25 matrix, built once",
    "cache/tokens_by_id": "article → tokens dict, built once",
    "cache/popularity_top_k": "static popularity top-20, built once",
    "stage2/nrms_parameters": "NRMS weights (float32)",
    "stage2/nrms_title_token_table": "title token ids, only needed to encode new articles",
    "stage2/article_vectors": "every article's NRMS vector, precomputed at start-up",
    "stage2/nrms_row_index": "article id → row dict",
    "stage2/click_timeline": "one int64 per click (popularity counts)",
    "stage2/publish_times": "float64 per article (freshness)",
}


def load(name: str) -> dict:
    return json.loads((REPORTS / name).read_text(encoding="utf-8"))


def f(x, nd=2) -> str:
    return f"{x:,.{nd}f}"


def table(header: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return out + [""]


def collect() -> dict:
    d = {"env": load("q4_environment.json"), "cost": load("q4_cost.json"),
         "repeat": load("q4_latency_repeatability.json")}
    for ds in DATASETS:
        d[f"correct_{ds}"] = load(f"q4_correctness_{ds}.json")
        d[f"mem_{ds}"] = load(f"q4_memory_{ds}.json")
        d[f"lat_{ds}"] = load(f"q4_latency_{ds}.json")
        d[f"scale_{ds}"] = load(f"q4_scale_{ds}.json")
    return d


def cost_row(d, ds, mode, qps, slowdown=1):
    return next(r for r in d["cost"]["datasets"][ds]["modes"][mode]["table"]
                if r["qps"] == qps and r["cloud_slowdown"] == slowdown)


# --------------------------------------------------------------------------- #
# summary
# --------------------------------------------------------------------------- #

def summary(d: dict) -> str:
    env, a = d["env"]["machine"], d["cost"]["assumptions"]
    L = ["# Q4 — Serving & scale analysis: results",
         "",
         "Generated by `src/serving/q4_report.py` from `reports/q4_*.json`. Reproduce everything with `make q4`.",
         "",
         "## Setup",
         "",
         f"- **System served:** the full two-stage pipeline. Stage 1 = BM25 top-80 ∪ FAISS top-100 (A1 embeddings) "
         f"∪ train-popularity top-20, deduplicated to ≤200 candidates from the circulating pool. Stage 2 = Q3 "
         f"popularity-aware NRMS (EB-NeRD adds freshness) → top-10.",
         f"- **Hardware:** {env['cpu']} ({env['cores_performance']} performance + {env['cores_efficiency']} efficiency "
         f"cores, {env['ram_gb']} GB RAM), CPU, **1 thread** (PyTorch, FAISS/OpenMP and BLAS pinned; "
         f"torch {env['torch']}, faiss {env['faiss']}).",
         f"- **Protocol:** start-up (indexes, model, every article's NRMS vector) is loaded once and never timed; "
         f"requests replay real (user, timestamp) pairs from the test split, one at a time.",
         "- **Two stage-1 modes, identical output (tested):** `as_is` calls the existing batch-evaluation functions "
         "per request; `serving` computes the parts that never change between requests once at start-up.",
         "",
         "## Correctness: the served path is the evaluated model",
         ""]
    L += table(["dataset", "impressions", "candidates", "max \\|serving − offline\\|", "tolerance", "same top-1"],
               [[LABEL[ds], d[f"correct_{ds}"]["n_impressions"], f"{d[f'correct_{ds}']['n_candidates']:,}",
                 f"{d[f'correct_{ds}']['max_abs_diff']:.1e}", d[f"correct_{ds}"]["tolerance"],
                 f"{100 * d[f'correct_{ds}']['top1_agreement']:.0f}%"] for ds in DATASETS])
    L += ["Stage-1 candidates in both modes equal `UnionRetriever.retrieve` exactly (`tests/test_serving.py`).", ""]

    # ---- memory ----
    L += ["## Q4.1 Memory", "", "### Structures a request reads (MB)", ""]
    names = list(d["mem_mind"]["components"])
    rows = []
    for n in names:
        rows.append([n.replace("/", " / "), WHAT.get(n, d["mem_mind"]["components"][n]["what"])] +
                    [f(d[f"mem_{ds}"]["components"][n]["mb"]) if n in d[f"mem_{ds}"]["components"] else "–"
                     for ds in DATASETS])
    for n in d["mem_ebnerd"]["components"]:
        if n not in names:
            rows.append([n.replace("/", " / "), WHAT.get(n, d["mem_ebnerd"]["components"][n]["what"]), "–",
                         f(d["mem_ebnerd"]["components"][n]["mb"])])
    rows.append(["**total served**", "", *[f"**{f(d[f'mem_{ds}']['summary']['served_total_mb'], 1)}**" for ds in DATASETS]])
    L += table(["component", "what", LABEL["mind"], LABEL["ebnerd"]], rows)

    L += ["### ANN index over the whole catalogue: flat vs HNSW", ""]
    L += table(["dataset", "articles × dims", "flat (exact) MB", "HNSW MB", "HNSW overhead", "HNSW build (1 thread)"],
               [[LABEL[ds], f"{d[f'mem_{ds}']['ann_index_option']['catalogue_articles']:,} × {d[f'mem_{ds}']['ann_index_option']['dims']}",
                 f(d[f"mem_{ds}"]["ann_index_option"]["flat_full_catalogue_mb"], 1),
                 f(d[f"mem_{ds}"]["ann_index_option"]["hnsw_full_catalogue_mb"], 1),
                 f"+{d[f'mem_{ds}']['ann_index_option']['hnsw_overhead_bytes_per_article']:.0f} B/article",
                 f"{d[f'mem_{ds}']['ann_index_option']['hnsw_build_seconds_1_thread']} s"] for ds in DATASETS])

    L += ["### Process RAM vs what serving needs", ""]
    L += table(["dataset", "runtime (imports)", "after load", "growth", "explained by components", "unexplained", "peak"],
               [[LABEL[ds]] + [f"{d[f'mem_{ds}']['process'][k]:,.0f} MB" for k in (
                   "rss_after_all_imports_mb", "rss_after_load_mb", "rss_growth_mb",
                   "growth_accounted_by_components_mb", "growth_unaccounted_mb", "peak_rss_mb")] for ds in DATASETS])
    L += ["The gap is memory the Q1/Q2 research loaders leave reserved after parsing raw files into Python objects, "
          "measured by running each loader alone in a fresh process:", ""]
    L += table(["dataset", "loader", "live result MB", "RAM left behind MB"],
               [[LABEL[ds], x["loader"], f(x["live_result_mb"], 1), f(x["rss_left_behind_mb"], 1)]
                for ds in DATASETS for x in d[f"mem_{ds}"].get("loader_residue", []) if "error" not in x])

    # ---- latency ----
    L += ["## Q4.2 Latency of one request", "",
          f"{d['lat_mind']['n_requests']:,} requests per dataset after {d['lat_mind']['warmup_requests']} discarded "
          "warm-up requests; both modes answer the same requests, order alternating.", ""]
    rows = []
    for ds in DATASETS:
        for mode in ("serving", "as_is"):
            t = d[f"lat_{ds}"]["modes"][mode]["total_ms"]
            rows.append([LABEL[ds], f"`{mode}`", f(t["mean"]), f(t["p50"]), f(t["p95"]), f"**{f(t['p99'])}**", f(t["max"]),
                         "✓" if d[f"lat_{ds}"]["modes"][mode]["meets_sla_p99"] else "✗"])
    L += table(["dataset", "mode", "mean ms", "p50", "p95", "p99", "max", f"p99 < {a['sla_p99_ms']} ms"], rows)
    L += [f"Serving speed-up over as-is: MIND {d['lat_mind']['serving_speedup_over_as_is']['p50']}× at p50, "
          f"{d['lat_mind']['serving_speedup_over_as_is']['p99']}× at p99; EB-NeRD "
          f"{d['lat_ebnerd']['serving_speedup_over_as_is']['p50']}× / {d['lat_ebnerd']['serving_speedup_over_as_is']['p99']}×.", ""]

    L += ["### Where the time goes (serving mode)", ""]
    L += table(["stage"] + [f"{LABEL[ds]} mean ms (share)" for ds in DATASETS] + [f"{LABEL[ds]} p99 ms" for ds in DATASETS],
               [[s] + [f"{d[f'lat_{ds}']['modes']['serving']['stages_ms'][s]['mean']:.3f} "
                       f"({100 * d[f'lat_{ds}']['modes']['serving']['stage_share_of_mean'][s]:.0f}%)" for ds in DATASETS]
                + [f"{d[f'lat_{ds}']['modes']['serving']['stages_ms'][s]['p99']:.3f}" for ds in DATASETS] for s in STAGES])

    L += ["### Tail latency grows with the user's history length (serving p99, ms)", "",
          "BM25's query is built from the words of the user's entire click history.", ""]
    bins = sorted({b for ds in DATASETS for b in d[f"lat_{ds}"]["modes"]["serving"]["by_history_length"]},
                  key=lambda b: int(b.split("-")[0]))
    L += table(["clicks in history"] + [LABEL[ds] for ds in DATASETS],
               [[b] + [(f"{d[f'lat_{ds}']['modes']['serving']['by_history_length'][b]['p99']:.2f} "
                        f"(n={d[f'lat_{ds}']['modes']['serving']['by_history_length'][b]['n']})")
                       if b in d[f"lat_{ds}"]["modes"]["serving"]["by_history_length"] else "–" for ds in DATASETS]
                for b in bins])

    s1 = d["scale_mind"]["scales"]["1"]
    L += ["### What makes `as_is` slow (MIND, measured separately, p99)", ""]
    L += table(["per-request work in as_is", "p99 ms"],
               [["`build_queries`: rebuild an article → tokens dict over the whole catalogue", f(s1["as_is_build_queries"]["latency_ms"]["p99"])],
                ["`PopularityRanker.top_k(allowed=…)`: Python scan of every article", f(s1["as_is_popularity_scan"]["latency_ms"]["p99"])],
                ["BM25 matrix re-cut to the pool + scoring (token list pre-built)", f(s1["bm25_as_is"]["latency_ms"]["p99"])]])

    L += ["### Repeatability (two full runs, run 2 vs run 1)", ""]
    L += table(["dataset", "mode", "p50", "p95", "p99", "max"],
               [[LABEL[ds], f"`{m}`"] + [f"{d['repeat']['runs'][ds][m][k]['change_pct']:+.1f}%" for k in ("p50", "p95", "p99", "max")]
                for ds in DATASETS for m in ("serving", "as_is")])

    # ---- cost ----
    L += ["## Q4.3 Cost and QPS", "",
          f"**Assumptions:** ${a['usd_per_core_hour']}/core-hour (sensitivity {a['price_sensitivity_usd_per_core_hour']}), "
          f"{int(100 * a['target_utilisation'])}% target utilisation, {a['ram_gb_per_vcpu']} GB RAM per vCPU, one single-threaded "
          f"worker process per core. **Not included:** {a['not_included']}.", "",
          "p99 under load comes from a queueing simulation: Poisson arrivals, first-free-core dispatch, service times "
          "resampled from the measured requests (checked against M/M/1 theory in `tests/test_cost_model.py`).", ""]
    rows = []
    for ds in DATASETS:
        for mode in ("serving", "as_is"):
            for qps in sorted({r["qps"] for r in d["cost"]["datasets"][ds]["modes"][mode]["table"]}):
                r = cost_row(d, ds, mode, qps)
                rows.append([LABEL[ds], f"`{mode}`", f"{qps:,}", r["cores"], f(r["sim_p99_ms"]),
                             f(r["ram_gb"], 1), f"${f(r['usd_per_hour'])}", f"${r['usd_per_month_24x7']:,.0f}",
                             f"${r['usd_per_1k_queries']:.6f}"])
    L += table(["dataset", "mode", "QPS", "cores", "sim p99 ms", "RAM GB", "$/hour", "$/month", "$ per 1k queries"], rows)

    L += ["### p99 against utilisation (8 cores, measured service times, ms)", ""]
    pts = d["cost"]["datasets"]["mind"]["modes"]["serving"]["utilisation_curve"]["points"]
    L += table(["dataset / mode"] + [f"{int(100 * p['utilisation'])}%" for p in pts] + ["highest meeting SLA"],
               [[f"{LABEL[ds]} `{m}`"] + [f(p["sim_p99_ms"]) for p in d["cost"]["datasets"][ds]["modes"][m]["utilisation_curve"]["points"]]
                + [f"{int(100 * d['cost']['datasets'][ds]['modes'][m]['utilisation_curve']['highest_utilisation_meeting_sla'])}%"]
                for ds in DATASETS for m in ("serving", "as_is")])

    L += ["### If a cloud vCPU is slower than an M4 core (serving, 10,000 QPS)", ""]
    L += table(["dataset", "slowdown", "cores", "sim p99 ms", "$ per 1k queries"],
               [[LABEL[ds], f"{sd}×", cost_row(d, ds, "serving", 10000, sd)["cores"],
                 f(cost_row(d, ds, "serving", 10000, sd)["sim_p99_ms"]),
                 f"${cost_row(d, ds, 'serving', 10000, sd)['usd_per_1k_queries']:.6f}"]
                for ds in DATASETS for sd in a["cloud_slowdown_factors"]])

    # ---- scale ----
    L += ["## Q4.4 Scale: 10× measured on a synthetic catalogue", "",
          f"Articles copied {d['scale_mind']['factor']}×, each copy's vector perturbed (σ = {d['scale_mind']['noise_std']}) and "
          f"re-normalised; BM25 rows, NRMS article vectors, pool and click events replicated. "
          f"{d['scale_mind']['n_queries']:,} real test users replayed against 1× and 10×. Index builds used every core; every timed "
          f"search used 1 thread. FAISS ran in a child process without PyTorch (duplicate OpenMP runtimes abort "
          f"multi-threaded FAISS when PyTorch is loaded). 1× totals are calibrated to Phase 3's measured mean.", ""]
    comp = [("BM25 (serving)", "bm25_serving"), ("FAISS flat over pool (served)", "faiss_flat_pool"),
            ("FAISS flat over whole catalogue", "faiss_flat_catalogue"), ("NRMS scoring", "nrms_scoring"),
            ("click counts", "click_timeline"), ("as_is: token dict rebuild", "as_is_build_queries"),
            ("as_is: popularity scan", "as_is_popularity_scan")]
    rows = []
    for label, k in comp:
        row = [label]
        for ds in DATASETS:
            o, t = d[f"scale_{ds}"]["scales"]["1"][k]["latency_ms"]["p99"], d[f"scale_{ds}"]["scales"]["10"][k]["latency_ms"]["p99"]
            row += [f"{f(o)} → {f(t)}"]
        rows.append(row)
    for label, k, sla_key in (("**serving total**", "serving_total_estimate_ms", None),
                              ("**as_is total**", "as_is_total_estimate_ms", "as_is_meets_sla_single_request")):
        row = [label]
        for ds in DATASETS:
            o, t = d[f"scale_{ds}"]["scales"]["1"][k]["p99"], d[f"scale_{ds}"]["scales"]["10"][k]["p99"]
            flag = "" if sla_key is None or d[f"scale_{ds}"]["scales"]["10"][sla_key] else " ✗ SLA"
            row += [f"**{f(o)} → {f(t)}**{flag}"]
        rows.append(row)
    L += table(["p99 ms, 1× → 10×"] + [f"{LABEL[ds]} ({d[f'scale_{ds}']['articles_1x']:,} → {d[f'scale_{ds}']['scales']['10']['articles']:,} articles)"
                                      for ds in DATASETS], rows)

    L += ["Sub-millisecond components (NRMS scoring, click counts) jitter by about ±0.2 ms between runs; "
          "their 1× → 10× ratios below 2× are within that noise.", "",
          "### HNSW recall@100 vs exact search, 1× → 10×", ""]
    efs = [e["ef_search"] for e in d["scale_mind"]["scales"]["1"]["hnsw_catalogue"]["ef_search"]]
    L += table(["efSearch"] + [f"{LABEL[ds]} recall" for ds in DATASETS] + [f"{LABEL[ds]} p99 ms at 10×" for ds in DATASETS],
               [[ef] + [f"{e1['recall_at_k']:.3f} → {e10['recall_at_k']:.3f}"
                        for ds in DATASETS
                        for e1, e10 in [(next(x for x in d[f'scale_{ds}']['scales']['1']['hnsw_catalogue']['ef_search'] if x['ef_search'] == ef),
                                         next(x for x in d[f'scale_{ds}']['scales']['10']['hnsw_catalogue']['ef_search'] if x['ef_search'] == ef))]]
                + [f(next(x for x in d[f'scale_{ds}']['scales']['10']['hnsw_catalogue']['ef_search'] if x['ef_search'] == ef)['latency_ms']['p99'])
                   for ds in DATASETS] for ef in efs])

    L += ["### Memory at 10×", ""]
    L += table(["dataset", "served 1× → 10× MB", "worker RAM 1× → 10× GB", f"fits {a['ram_gb_per_vcpu']} GB/vCPU", "HNSW over 10× catalogue MB"],
               [[LABEL[ds], f"{d[f'scale_{ds}']['memory_10x']['served_1x_mb']:,.0f} → {d[f'scale_{ds}']['memory_10x']['served_10x_mb']:,.0f}",
                 f"{d[f'scale_{ds}']['memory_10x']['worker_ram_1x_gb']} → {d[f'scale_{ds}']['memory_10x']['worker_ram_10x_gb']}",
                 "✓" if d[f"scale_{ds}"]["memory_10x"]["fits_one_vcpu_share_at_10x"] else "✗",
                 f"{d[f'scale_{ds}']['memory_10x']['hnsw_catalogue_10x_mb']:,.0f}"] for ds in DATASETS])

    L += ["### Scenarios (serving mode)", ""]
    L += table(["dataset", "scenario", "QPS", "CPU cores", "RAM GB", "billed vCPUs", "limited by", "sim p99 ms", "$/hour"],
               [[LABEL[ds], s["scenario"], f"{s['qps']:,}", s["cores_for_cpu"], f(s["ram_gb"], 1), s["billed_vcpus"],
                 s["binding_constraint"], f(s["sim_p99_ms"]), f"${f(s['usd_per_hour'])}"]
                for ds in DATASETS for s in d[f"scale_{ds}"]["scenarios"]])

    L += ["## Caveats", "",
          "- Laptop, not a server: Apple M4, 1 thread; macOS may schedule on efficiency cores, and numpy's BLAS "
          "(Accelerate) offloads to the AMX coprocessor, so per-core figures are indicative, not cloud-vCPU exact.",
          "- Only the in-process pipeline is timed: no network, request parsing, or remote profile/click-counter stores.",
          "- The circulating candidate pool is built from the whole test period (inherited from Q2's retriever): slightly "
          "optimistic for recall, no effect on latency or memory.",
          *[f"- {c}" for c in d["scale_mind"]["caveats"]], ""]
    return "\n".join(L)


# --------------------------------------------------------------------------- #
# design-note section
# --------------------------------------------------------------------------- #

def design_note(d: dict) -> str:
    a = d["cost"]["assumptions"]
    lm, le = d["lat_mind"]["modes"], d["lat_ebnerd"]["modes"]
    mm, me = d["mem_mind"], d["mem_ebnerd"]
    sm, se = d["scale_mind"], d["scale_ebnerd"]
    s1, s10 = sm["scales"]["1"], sm["scales"]["10"]
    cm1k, ce1k = cost_row(d, "mind", "serving", 1000), cost_row(d, "ebnerd", "serving", 1000)
    cm10k, ce10k = cost_row(d, "mind", "serving", 10000), cost_row(d, "ebnerd", "serving", 10000)
    am1k = cost_row(d, "mind", "as_is", 1000)
    ef64 = lambda s, sc: next(x for x in s["scales"][sc]["hnsw_catalogue"]["ef_search"] if x["ef_search"] == 64)  # noqa: E731
    ef256 = lambda s, sc: next(x for x in s["scales"][sc]["hnsw_catalogue"]["ef_search"] if x["ef_search"] == 256)  # noqa: E731
    scen = {s["scenario"]: s for s in sm["scenarios"]}
    both = scen["10x catalogue and 10x traffic"]
    env = d["env"]["machine"]

    return "\n".join([
        "## 4. Serving and scale",
        "",
        "*Generated by `src/serving/q4_report.py` from `reports/q4_*.json`; full tables in `reports/q4_summary.md`.*",
        "",
        "### 4.1 What was measured",
        "",
        f"We served the full two-stage pipeline for one request at a time: stage 1 retrieves up to 200 candidates "
        f"(BM25 top-80 ∪ FAISS top-100 over A1 embeddings ∪ popularity top-20, from the circulating pool) and stage 2 "
        f"re-ranks them with the Q3 popularity-aware NRMS. Everything a request reads is loaded once at start-up, "
        f"including every article's NRMS vector, so a request never encodes text. Measurements ran on an {env['cpu']} "
        f"CPU with PyTorch, FAISS and BLAS pinned to one thread. The served path reproduces the offline test scores "
        f"(max difference {d['correct_mind']['max_abs_diff']:.0e} on MIND, {d['correct_ebnerd']['max_abs_diff']:.0e} on "
        f"EB-NeRD; identical top-1), so the numbers describe the evaluated model.",
        "",
        "### 4.2 Memory",
        "",
        f"Serving needs **{mm['summary']['served_total_mb']:.0f} MB on MIND** and **{me['summary']['served_total_mb']:.0f} MB on "
        f"EB-NeRD**. The two largest items are per-article vectors: A1 embeddings for retrieval "
        f"({mm['components']['stage1/a1_article_embeddings']['mb']:.0f} MB) and NRMS article vectors for re-ranking "
        f"({mm['components']['stage2/article_vectors']['mb']:.0f} MB); NRMS weights are "
        f"{mm['components']['stage2/nrms_parameters']['mb']:.0f} MB. An exact FAISS index over MIND's whole catalogue is "
        f"{mm['ann_index_option']['flat_full_catalogue_mb']:.0f} MB; HNSW (M={mm['ann_index_option']['hnsw_m']}) adds "
        f"{mm['ann_index_option']['hnsw_overhead_bytes_per_article']:.0f} bytes per article "
        f"({mm['ann_index_option']['hnsw_full_catalogue_mb']:.0f} MB). The research process itself is far larger "
        f"({mm['process']['rss_after_load_mb']:,.0f} MB MIND, {me['process']['rss_after_load_mb']:,.0f} MB EB-NeRD) because the "
        f"Q1/Q2 loaders parse raw files into Python objects and leave that memory reserved; isolated, EB-NeRD's word2vec "
        f"loader keeps a {next(x for x in me['loader_residue'] if x['loader'] == 'provided_word2vec')['live_result_mb']:.0f} MB "
        f"result but leaves {next(x for x in me['loader_residue'] if x['loader'] == 'provided_word2vec')['rss_left_behind_mb']:.0f} MB "
        f"behind. A production server would load prebuilt serving artifacts instead.",
        "",
        "### 4.3 Latency",
        "",
        f"Over {d['lat_mind']['n_requests']:,} replayed test requests per dataset, one request takes **p50 "
        f"{lm['serving']['total_ms']['p50']:.2f} ms / p99 {lm['serving']['total_ms']['p99']:.2f} ms on MIND** and **p50 "
        f"{le['serving']['total_ms']['p50']:.2f} ms / p99 {le['serving']['total_ms']['p99']:.2f} ms on EB-NeRD**, far under a "
        f"{a['sla_p99_ms']} ms p99 target; a second full run reproduced serving-mode p50–p99 within "
        f"{max(abs(d['repeat']['runs'][ds]['serving'][k]['change_pct']) for ds in DATASETS for k in ('p50', 'p95', 'p99')):.0f}%. BM25 is the "
        f"largest stage ({100 * lm['serving']['stage_share_of_mean']['bm25']:.0f}% of MIND's mean, "
        f"{100 * le['serving']['stage_share_of_mean']['bm25']:.0f}% of EB-NeRD's) and sets the tail, because its query is "
        f"built from the user's whole click history; NRMS re-ranking is a constant ~"
        f"{lm['serving']['stages_ms']['nrms']['mean']:.1f} ms because it only scores 200 precomputed vectors. "
        f"Calling the existing batch-evaluation functions per request instead (`as_is`) costs p99 "
        f"{lm['as_is']['total_ms']['p99']:.1f} ms on MIND ({d['lat_mind']['serving_speedup_over_as_is']['p50']}× slower at p50): "
        f"almost all of it is `build_queries` rebuilding a token dictionary over every article "
        f"(p99 {s1['as_is_build_queries']['latency_ms']['p99']:.1f} ms) and a Python scan of every article for popularity "
        f"({s1['as_is_popularity_scan']['latency_ms']['p99']:.1f} ms), not the BM25 matrix itself "
        f"({s1['bm25_as_is']['latency_ms']['p99']:.1f} ms).",
        "",
        "### 4.4 Cost",
        "",
        f"With one single-threaded worker per core at {int(100 * a['target_utilisation'])}% utilisation and an assumed "
        f"${a['usd_per_core_hour']} per core-hour, 1,000 QPS needs **{cm1k['cores']} cores on MIND and {ce1k['cores']} on "
        f"EB-NeRD** (as_is MIND: {am1k['cores']}), about **${cm1k['usd_per_1k_queries']:.5f} / ${ce1k['usd_per_1k_queries']:.5f} "
        f"per 1,000 queries**; 10,000 QPS "
        f"needs {cm10k['cores']} / {ce10k['cores']} cores (${cm10k['usd_per_month_24x7']:,.0f} / "
        f"${ce10k['usd_per_month_24x7']:,.0f} per month). A queueing simulation driven by the measured request times "
        f"gives p99 {cm1k['sim_p99_ms']:.1f} ms (MIND) and {ce1k['sim_p99_ms']:.1f} ms (EB-NeRD) at 1,000 QPS; MIND serving-mode p99 only reaches "
        f"{d['cost']['datasets']['mind']['modes']['serving']['utilisation_curve']['points'][-1]['sim_p99_ms']:.0f} ms at 95% "
        f"utilisation, so the SLA is not the binding constraint — cost is. Even if a cloud vCPU were 3× slower than an M4 "
        f"core, serving MIND at 10,000 QPS stays under {cost_row(d, 'mind', 'serving', 10000, 3)['sim_p99_ms']:.0f} ms p99 "
        f"with {cost_row(d, 'mind', 'serving', 10000, 3)['cores']} cores. Worker RAM ({d['cost']['datasets']['mind']['worker_ram_gb']} GB "
        f"MIND) fits within {a['ram_gb_per_vcpu']} GB per vCPU, so CPU sets the price today.",
        "",
        "### 4.5 Where it breaks at 10×",
        "",
        f"We built a synthetic 10× catalogue (perturbed copies of every article; {sm['articles_1x']:,} → "
        f"{s10['articles']:,} on MIND) and replayed {sm['n_queries']:,} real users. In order:",
        "",
        f"1. **Per-request code that touches every article.** `as_is` MIND p99 goes from "
        f"{s1['as_is_total_estimate_ms']['p99']:.0f} ms to **{s10['as_is_total_estimate_ms']['p99']:.0f} ms** and breaks the SLA "
        f"on a single request (EB-NeRD: {se['scales']['10']['as_is_total_estimate_ms']['p99']:.0f} ms, just under it with "
        f"no headroom for queueing). Caching the request-independent parts removes this: serving p99 only grows "
        f"{s1['serving_total_estimate_ms']['p99']:.1f} → {s10['serving_total_estimate_ms']['p99']:.1f} ms.",
        f"2. **RAM per worker.** Served structures grow {sm['memory_10x']['served_1x_mb']:.0f} MB → "
        f"{sm['memory_10x']['served_10x_mb']:,.0f} MB, so each MIND worker needs {sm['memory_10x']['worker_ram_10x_gb']} GB — more "
        f"than {a['ram_gb_per_vcpu']} GB per vCPU — and RAM rather than CPU sets the bill "
        f"({both['billed_vcpus']} vCPUs for {both['cores_for_cpu']} cores of work at 10× catalogue and 10× traffic). Fix: share "
        f"read-only vectors across workers (memory-mapped files) or move them to a vector-search service.",
        f"3. **Approximate-search quality.** Exact search over the whole MIND catalogue grows to "
        f"{s10['faiss_flat_catalogue']['latency_ms']['p99']:.0f} ms p99 at 10×, pushing a larger site to HNSW — whose "
        f"recall@100 falls from {ef64(sm, '1')['recall_at_k']:.2f} to {ef64(sm, '10')['recall_at_k']:.2f} at efSearch 64 "
        f"({ef256(sm, '10')['recall_at_k']:.2f} even at 256; EB-NeRD {ef64(se, '1')['recall_at_k']:.2f} → "
        f"{ef64(se, '10')['recall_at_k']:.2f}). Our design avoids this today by searching only the circulating pool "
        f"({s10['faiss_flat_pool']['latency_ms']['p99']:.1f} ms at 10×), but that pool grows with the site.",
        f"4. **Not the bottleneck:** stage-2 re-ranking ({s1['nrms_scoring']['latency_ms']['p99']:.2f} → "
        f"{s10['nrms_scoring']['latency_ms']['p99']:.2f} ms) and click-count lookups stay flat; 10× traffic alone is a linear "
        f"cost ({scen['today: 1x catalogue, 1,000 QPS']['billed_vcpus']} → {scen['10x traffic only']['billed_vcpus']} vCPUs) "
        f"with lower p99 from larger pools. Not measured: ingesting 10× click events needs a streaming counter, and start-up "
        f"(encoding every article, building indexes) grows linearly.",
        "",
        "Caveats: laptop CPU (indicative per-core numbers), no network or remote stores in the timings, synthetic "
        "near-duplicate copies make 10× HNSW recall pessimistic and do not grow BM25's vocabulary, users ×10 is a linear "
        "memory extrapolation.",
        "",
    ])


def main() -> int:
    d = collect()
    (REPORTS / "q4_summary.md").write_text(summary(d), encoding="utf-8")
    (REPORTS / "design_note_q4.md").write_text(design_note(d), encoding="utf-8")
    print(f"-> {REPORTS / 'q4_summary.md'}\n-> {REPORTS / 'design_note_q4.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
